[project]
name = "pyrpl-change"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Sinclair Lab", email = "sinclairquantumlab@gmail.com" }
]
requires-python = "==3.8.*"
dependencies = [
    "scp",
    "matplotlib",
    "scipy>=1.2",
    "pyyaml",
    "pandas",
    "pyqtgraph",
    "numpy>=1.9",
    "paramiko>=2.0",
    "nose>=1.0",
    "pyqt5",
    "qtpy",
    "nbconvert",
    "jupyter-client",
    "netifaces",
    "lmfit>=1.0.1",
    "quamash",
]

[project.scripts]
pyrpl-change = "pyrpl_change:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
required-environments = ["sys_platform == 'win32' and platform_machine == 'AMD64'"]